name: CI/CD Pipeline

on: [push]

env:
  ATERA_API_KEY: ${{ secrets.ATERA_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache-dependency-path: '**/*.csproj'
          
      - name: Build and Test
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        env:
          Atera__ApiKey: ${{ env.ATERA_API_KEY }}
        
      - name: Docker Build
        run: |
          ./scripts/docker-build.sh
          docker image prune -f
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Integration Test
        run: |
          echo 'Testing MCP server version:'
          echo '{"jsonrpc":"2.0","method":"mcp-version","id":1}' | \
            docker run --rm -i atera-mcp
          
          echo 'Running full test suite:'
          docker run --rm -e Atera__ApiKey=${{ env.ATERA_API_KEY }} \
            atera-mcp dotnet test AteraMcp.IntegrationTests.dll
